import os

MAIN_DYNAMO_CREDENTIALS = "MAIN"
BACKUP_DYNAMO_CREDENTIALS = "MAINBACKUP"

TABLE_CREDENTIALS = os.environ['TABLE_CREDENTIALS']
TABLE_DATA = os.environ['TABLE_DATA']

USERNAME_SMTP = "AKIA6LJ5TBJFPFJYHY6K"
PASSWORD_SMTP = "BDQ+7bG7tqvrnDebVyjo9VeYSqTFPbQwL5ylzOEtRRDN"
CONFIGURATION_SET = "analyticsS3"
SENDER = 'tech@ubits.co'
SENDER_NAME = 'Tech Ubits Learning'
RECIPIENT = 'rgarcia@ubits.co'